### PR TITLE
Profile page

### LINKED ISSUE #22: Make a new static page [pipen95]
* before making changes on your local machine create new branch:
` git checkout -b your_name_dev`

The task is to create new static page in that project to be able to access the page at localhost:3000/***your_name***

It can be achieved by the following steps:

1. find a controller responsible for current index page
2. make a new empty method with the name ***your_name***
3. create a view file for this method, add some text, style it
4. add new get request in config/routes.rb to be able visit this page at localhost:3000/***your_name***

When finished:
- commit, push
- make a pull request

### PR DESCRIPTION
**Pull request by pipen95**
Fix #22 

I finished my profile page. Let me know what you think. Thks

### CODE REVIEW

**Review by uzorjchibuzor — CHANGES_REQUESTED** [review]
@pipen95 Why are you creating a css file? replicate the ul>li that is on /members page

**Comment by uzorjchibuzor** [comment]
Screen Shot 2022-07-02 at 5 03 09 PM

I was against custom css but I can argue against this design. Nice.

**Comment by czepesch** [comment]
I think we can live with custom css for now)
Good job

**Comment by uzorjchibuzor** [comment]
I approve this.

**Review by uzorjchibuzor — APPROVED** [review]

**Pull request merged**
